name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    # Allow the job to fetch a GitHub ID token
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/569757135820/locations/global/workloadIdentityPools/github/providers/github_provider'
          service_account: 'github-actions-build-deploy@deep-voyage-436902-b3.iam.gserviceaccount.com'
          audience: '//iam.googleapis.com/projects/569757135820/locations/global/workloadIdentityPools/github/providers/github_provider'
          

