name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Step 3: Authenticate Docker to use Google Container Registry
    - name: Authenticate Docker
      run: gcloud auth configure-docker

    # Step 4: Submit the build to Cloud Build
    - name: Build image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/svelte-sql-gcp

    # Step 5: Deploy to Cloud Run
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy daves-sveltekit-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/svelte-sql-gcp \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --add-cloudsql-instances ${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:svelte-test
