name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main

jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
#jobs:
  #deploy:
    #runs-on: ubuntu-latest

   # steps:
    # Step 1: Check out the repository
   # - name: Checkout code
   #   uses: actions/checkout@v4

    # Step 2: Authenticate with Google Cloud
   # - name: Authenticate
 #     uses: 'google-github-actions/auth@v2'
  #    with:
 #       credentials_json: ${{ secrets.GCP_SA_KEY }}

    # Step 2: Setup Google Cloud SDK
  #  - name: Set up Google Cloud SDK
 #     uses: google-github-actions/setup-gcloud@v1
 #     with:
#        project_id: ${{ secrets.GCP_PROJECT_ID }}
#        service_account_key: ${{ secrets.GCP_SA_KEY }}
#        export_default_credentials: true
        
    # Step 3: Submit the build to Cloud Build
#    - name: Build image
#      run: |
#        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/svelte-sql-gcp \
#        --impersonate-service-account=github-actions-build-deploy@${{secrets.GCP_PROJECT_ID}}.iam.gserviceaccount.com

    # Step 4: Deploy to Cloud Run
#    - name: Deploy to Cloud Run
#      run: |
#        gcloud run deploy daves-sveltekit-app \
#          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/svelte-sql-gcp \
#          --platform managed \
 #         --region ${{ secrets.GCP_REGION }} \
 #         --allow-unauthenticated \
 #         --add-cloudsql-instances ${{ secrets.GCP_PROJECT_ID }}:${{ secrets.GCP_REGION }}:svelte-test
